# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\4th year\Second Term\Advanced MRI\Tasks\MRI-Phantom\src\ui\Phantom.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 789)
        Form.setMinimumSize(QtCore.QSize(0, 100))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.widget_sequence = QtWidgets.QWidget(self.tab_1)
        self.widget_sequence.setObjectName("widget_sequence")
        self.verticalLayout_4.addWidget(self.widget_sequence)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.widget_4 = QtWidgets.QWidget(self.tab_1)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.groupBox = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_openSequence = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_openSequence.setFont(font)
        self.pushButton_openSequence.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../docs/icons/open folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_openSequence.setIcon(icon)
        self.pushButton_openSequence.setObjectName("pushButton_openSequence")
        self.horizontalLayout_6.addWidget(self.pushButton_openSequence)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.spinBox_RF = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_RF.setObjectName("spinBox_RF")
        self.horizontalLayout_6.addWidget(self.spinBox_RF)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinBox_TR = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_TR.setObjectName("spinBox_TR")
        self.horizontalLayout_6.addWidget(self.spinBox_TR)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_apply = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_apply.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_apply.setFont(font)
        self.pushButton_apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_apply.setDefault(True)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout_6.addWidget(self.pushButton_apply)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear.setStyleSheet("background-color: rgb(222, 0, 0);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_6.addWidget(self.pushButton_clear)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(9, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_1)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.tab_1)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_pixel = QtWidgets.QLabel(self.tab_1)
        self.label_pixel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pixel.setObjectName("label_pixel")
        self.verticalLayout_2.addWidget(self.label_pixel)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_1)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab_1)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(165, 29, 45)")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.comboBox_contrastType = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_contrastType.setObjectName("comboBox_contrastType")
        self.comboBox_contrastType.addItem("")
        self.comboBox_contrastType.addItem("")
        self.comboBox_contrastType.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_contrastType)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.horizontalSlider_brightness = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_brightness.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalSlider_brightness.setMinimum(-127)
        self.horizontalSlider_brightness.setMaximum(127)
        self.horizontalSlider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_brightness.setObjectName("horizontalSlider_brightness")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_brightness)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalSlider_contrast = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_contrast.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalSlider_contrast.setMinimum(-100)
        self.horizontalSlider_contrast.setMaximum(100)
        self.horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_contrast.setObjectName("horizontalSlider_contrast")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_contrast)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.comboBox_kspace_size = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_kspace_size.setFont(font)
        self.comboBox_kspace_size.setObjectName("comboBox_kspace_size")
        self.comboBox_kspace_size.addItem("")
        self.comboBox_kspace_size.addItem("")
        self.comboBox_kspace_size.addItem("")
        self.comboBox_kspace_size.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_kspace_size)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_openPhantom = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_openPhantom.setFont(font)
        self.pushButton_openPhantom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_openPhantom.setIcon(icon)
        self.pushButton_openPhantom.setObjectName("pushButton_openPhantom")
        self.horizontalLayout_4.addWidget(self.pushButton_openPhantom)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.pushButton_startReconstruct = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_startReconstruct.setMinimumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_startReconstruct.setFont(font)
        self.pushButton_startReconstruct.setObjectName("pushButton_startReconstruct")
        self.horizontalLayout_4.addWidget(self.pushButton_startReconstruct)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(11, 1)
        self.horizontalLayout_4.setStretch(13, 1)
        self.horizontalLayout_4.setStretch(15, 2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(2, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.label_viewerOne = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_viewerOne.setFont(font)
        self.label_viewerOne.setObjectName("label_viewerOne")
        self.verticalLayout_3.addWidget(self.label_viewerOne, 0, QtCore.Qt.AlignHCenter)
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.label_viewerTwo = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_viewerTwo.setFont(font)
        self.label_viewerTwo.setObjectName("label_viewerTwo")
        self.verticalLayout_5.addWidget(self.label_viewerTwo, 0, QtCore.Qt.AlignHCenter)
        self.widget_7 = QtWidgets.QWidget(self.tab_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.label_progress = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_progress.setFont(font)
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout_7.addWidget(self.label_progress, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.comboBox_viewer = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_viewer.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_viewer.setObjectName("comboBox_viewer")
        self.comboBox_viewer.addItem("")
        self.comboBox_viewer.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_viewer)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.pushButton_Draw = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Draw.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Draw.setFont(font)
        self.pushButton_Draw.setObjectName("pushButton_Draw")
        self.horizontalLayout_2.addWidget(self.pushButton_Draw)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_kspace_size.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Loaded Sequence"))
        self.label_7.setText(_translate("Form", "Custom Sequence"))
        self.groupBox.setTitle(_translate("Form", "Sequence Control"))
        self.pushButton_openSequence.setText(_translate("Form", " Load "))
        self.label.setText(_translate("Form", "RF"))
        self.label_2.setText(_translate("Form", "TR"))
        self.pushButton_apply.setText(_translate("Form", "Apply"))
        self.pushButton_clear.setText(_translate("Form", "Clear All"))
        self.label_3.setText(_translate("Form", "Original Image"))
        self.label_8.setText(_translate("Form", "Fourier"))
        self.label_pixel.setText(_translate("Form", "<html><head/><body><p>Pixel PD Value at :</p></body></html>"))
        self.label_4.setText(_translate("Form", "K-Space"))
        self.label_5.setText(_translate("Form", "Reconstructed Image"))
        self.groupBox_2.setTitle(_translate("Form", "Contrast Control"))
        self.comboBox_contrastType.setItemText(0, _translate("Form", "PD"))
        self.comboBox_contrastType.setItemText(1, _translate("Form", "T1"))
        self.comboBox_contrastType.setItemText(2, _translate("Form", "T2"))
        self.label_9.setText(_translate("Form", "Brightness"))
        self.label_11.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "Contrast"))
        self.label_12.setText(_translate("Form", "0"))
        self.comboBox_kspace_size.setItemText(0, _translate("Form", "16"))
        self.comboBox_kspace_size.setItemText(1, _translate("Form", "32"))
        self.comboBox_kspace_size.setItemText(2, _translate("Form", "64"))
        self.comboBox_kspace_size.setItemText(3, _translate("Form", "128"))
        self.pushButton_openPhantom.setText(_translate("Form", " Open"))
        self.pushButton_startReconstruct.setText(_translate("Form", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "Phantom Viewer"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa0000;\">Viewer 1</span></p></body></html>"))
        self.label_viewerOne.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Prep + Seq</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa0000;\">Viewer 2</span></p></body></html>"))
        self.label_viewerTwo.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Prep + Seq</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Form", "No Prep"))
        self.comboBox_2.setItemText(1, _translate("Form", "IR Prep"))
        self.comboBox_2.setItemText(2, _translate("Form", "T2 Prep"))
        self.comboBox_2.setItemText(3, _translate("Form", "D Tagging Prep"))
        self.comboBox_2.setItemText(4, _translate("Form", "H Tagging Prep"))
        self.comboBox_2.setItemText(5, _translate("Form", "V Tagging Prep"))
        self.comboBox_3.setItemText(0, _translate("Form", "GRE Seq"))
        self.comboBox_3.setItemText(1, _translate("Form", "Spin Echo Seq"))
        self.comboBox_3.setItemText(2, _translate("Form", "Turbo Spin Echo Seq"))
        self.comboBox_3.setItemText(3, _translate("Form", "SSFP Seq"))
        self.comboBox_viewer.setItemText(0, _translate("Form", "Viewer 1"))
        self.comboBox_viewer.setItemText(1, _translate("Form", "Viewer 2"))
        self.pushButton_Draw.setText(_translate("Form", "DRAW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sequence Drawer"))

